# Generated by Django 4.0.1 on 2022-03-03 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0002_stoke_delete_tractors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stoke',
            name='Username',
        ),
        migrations.AddField(
            model_name='stoke',
            name='ChassisNumber',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='stoke',
            name='Details',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='stoke',
            name='HP',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='stoke',
            name='KMDriven',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='stoke',
            name='Model',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='stoke',
            name='No',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='stoke',
            name='RCBook',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='stoke',
            name='RTO',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='stoke',
            name='RegistrationNO',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='stoke',
            name='TractorName',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
