# Generated by Django 4.0.1 on 2022-03-04 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0003_remove_stoke_username_stoke_chassisnumber_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='index',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20, null=True)),
                ('dest', models.CharField(blank=True, max_length=4, null=True)),
            ],
        ),
    ]
