# Generated by Django 4.0.1 on 2022-03-04 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0005_index_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='index',
            name='upload',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
