# Generated by Django 4.0.1 on 2022-03-07 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0006_alter_index_upload'),
    ]

    operations = [
        migrations.AddField(
            model_name='index',
            name='model',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
