# Generated by Django 4.0.1 on 2022-03-07 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0007_index_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='index',
            name='dest',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='index',
            name='name',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
