# Generated by Django 4.0.1 on 2022-03-07 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0008_alter_index_dest_alter_index_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='index',
            name='dest',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
