# Generated by Django 4.0.1 on 2022-03-07 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0009_alter_index_dest'),
    ]

    operations = [
        migrations.CreateModel(
            name='BRAND_OF_THE_MONTH',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('HP1', models.CharField(blank=True, max_length=2, null=True)),
                ('CC', models.CharField(blank=True, max_length=4, null=True)),
                ('NOOFCYLINDER', models.CharField(blank=True, max_length=2, null=True)),
                ('GEARBOXTYPE', models.CharField(blank=True, max_length=8, null=True)),
                ('PTO', models.CharField(blank=True, max_length=2, null=True)),
            ],
        ),
    ]
