# Generated by Django 4.0.1 on 2022-03-07 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0010_brand_of_the_month'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BRAND_OF_THE_MONTH',
            new_name='BRANDOFTHEMONTH',
        ),
    ]
