# Generated by Django 4.0.1 on 2022-03-08 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0011_rename_brand_of_the_month_brandofthemonth'),
    ]

    operations = [
        migrations.RenameField(
            model_name='index',
            old_name='model',
            new_name='KMDriveni',
        ),
        migrations.RenameField(
            model_name='index',
            old_name='name',
            new_name='Regnoi',
        ),
        migrations.RenameField(
            model_name='index',
            old_name='dest',
            new_name='desti',
        ),
        migrations.AddField(
            model_name='index',
            name='ChassisNumberi',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='index',
            name='RCi',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='index',
            name='modeli',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='index',
            name='namei',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
