# Generated by Django 4.0.1 on 2022-03-13 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0013_rename_chassisnumberi_index_chassisnumber_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BRING',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NAMEB', models.CharField(blank=True, max_length=4, null=True)),
                ('HPB', models.CharField(blank=True, max_length=2, null=True)),
                ('CCB', models.CharField(blank=True, max_length=4, null=True)),
                ('GEARB', models.CharField(blank=True, max_length=8, null=True)),
                ('PTOB', models.CharField(blank=True, max_length=2, null=True)),
            ],
        ),
    ]
