# Generated by Django 4.0.1 on 2022-03-14 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0014_bring'),
    ]

    operations = [
        migrations.RenameField(
            model_name='index',
            old_name='dest',
            new_name='HP',
        ),
    ]
