# Generated by Django 4.0.1 on 2022-03-14 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0015_rename_dest_index_hp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='index',
            old_name='KMDriven',
            new_name='dest',
        ),
        migrations.RemoveField(
            model_name='index',
            name='ChassisNumber',
        ),
        migrations.RemoveField(
            model_name='index',
            name='RC',
        ),
        migrations.RemoveField(
            model_name='index',
            name='Regno',
        ),
        migrations.RemoveField(
            model_name='index',
            name='model',
        ),
    ]
