# Generated by Django 4.0.1 on 2022-03-14 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0016_rename_kmdriven_index_dest_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='index',
            name='HP',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='index',
            name='dest',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
