# Generated by Django 4.0.1 on 2022-03-14 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0017_alter_index_hp_alter_index_dest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='index',
            name='dest',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
