# Generated by Django 4.0.1 on 2022-03-14 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0018_alter_index_dest'),
    ]

    operations = [
        migrations.AddField(
            model_name='index',
            name='Regno',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
