# Generated by Django 4.0.1 on 2022-03-14 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0019_index_regno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='index',
            name='Regno',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
