# Generated by Django 4.0.1 on 2022-03-14 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0020_alter_index_regno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='index',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
