# Generated by Django 4.0.1 on 2022-03-14 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0021_alter_index_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='OLDTRACTOR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload', models.ImageField(blank=True, null=True, upload_to='images')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('HP', models.CharField(blank=True, max_length=2, null=True)),
                ('dest', models.CharField(blank=True, max_length=100, null=True)),
                ('Regno', models.CharField(blank=True, max_length=200, null=True)),
                ('RC', models.CharField(blank=True, max_length=3, null=True)),
                ('KMDriven', models.CharField(blank=True, max_length=4, null=True)),
                ('ChassisNumber', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
