# Generated by Django 4.0.1 on 2022-03-22 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0022_oldtractor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='oldtractor',
            old_name='ChassisNumber',
            new_name='ChassisNumberO',
        ),
        migrations.RenameField(
            model_name='oldtractor',
            old_name='HP',
            new_name='HPO',
        ),
        migrations.RenameField(
            model_name='oldtractor',
            old_name='KMDriven',
            new_name='KMDrivenO',
        ),
        migrations.RenameField(
            model_name='oldtractor',
            old_name='RC',
            new_name='RCO',
        ),
        migrations.RenameField(
            model_name='oldtractor',
            old_name='Regno',
            new_name='RegnoO',
        ),
        migrations.RenameField(
            model_name='oldtractor',
            old_name='dest',
            new_name='destO',
        ),
        migrations.RenameField(
            model_name='oldtractor',
            old_name='name',
            new_name='nameO',
        ),
        migrations.RenameField(
            model_name='oldtractor',
            old_name='upload',
            new_name='uploadO',
        ),
    ]
