# Generated by Django 4.0.1 on 2022-03-23 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0023_rename_chassisnumber_oldtractor_chassisnumbero_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='pics')),
                ('dest', models.TextField()),
            ],
        ),
    ]
