# Generated by Django 4.0.1 on 2022-03-23 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0024_destination'),
    ]

    operations = [
        migrations.RenameField(
            model_name='index',
            old_name='Regno',
            new_name='urls',
        ),
    ]
