# Generated by Django 4.0.1 on 2022-03-24 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0025_rename_regno_index_urls'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oldtractor',
            name='ChassisNumberO',
        ),
    ]
