# Generated by Django 4.0.1 on 2022-03-24 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0026_remove_oldtractor_chassisnumbero'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oldtractor',
            name='destO',
        ),
        migrations.AddField(
            model_name='oldtractor',
            name='yearO',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='oldtractor',
            name='RegnoO',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='oldtractor',
            name='nameO',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
