# Generated by Django 4.0.1 on 2022-03-24 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0028_inspection'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BRANDOFTHEMONTH',
        ),
        migrations.DeleteModel(
            name='BRING',
        ),
    ]
