# Generated by Django 4.0.1 on 2022-03-24 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0029_delete_brandofthemonth_delete_bring'),
    ]

    operations = [
        migrations.RenameField(
            model_name='oldtractor',
            old_name='HPO',
            new_name='HP',
        ),
        migrations.RenameField(
            model_name='oldtractor',
            old_name='KMDrivenO',
            new_name='KMDriven',
        ),
        migrations.RenameField(
            model_name='oldtractor',
            old_name='RCO',
            new_name='RC',
        ),
        migrations.RenameField(
            model_name='oldtractor',
            old_name='RegnoO',
            new_name='Regno',
        ),
        migrations.RenameField(
            model_name='oldtractor',
            old_name='nameO',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='oldtractor',
            old_name='uploadO',
            new_name='upload',
        ),
        migrations.RenameField(
            model_name='oldtractor',
            old_name='yearO',
            new_name='year',
        ),
    ]
