# Generated by Django 4.0.1 on 2022-03-24 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0030_rename_hpo_oldtractor_hp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='oldtractor',
            name='price',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
