# Generated by Django 4.0.1 on 2022-03-24 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0032_inspection_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='oldtractor',
            name='Hours',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
