# Generated by Django 4.0.1 on 2022-03-25 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0034_alter_oldtractor_hp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oldtractor',
            name='year',
            field=models.IntegerField(blank=True, max_length=2, null=True),
        ),
    ]
