# Generated by Django 4.0.1 on 2022-03-25 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0035_alter_oldtractor_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oldtractor',
            name='Hours',
            field=models.IntegerField(blank=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='oldtractor',
            name='KMDriven',
            field=models.IntegerField(blank=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='oldtractor',
            name='price',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
