# Generated by Django 4.0.1 on 2022-03-25 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0036_alter_oldtractor_hours_alter_oldtractor_kmdriven_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oldtractor',
            name='year',
            field=models.IntegerField(blank=True, max_length=4, null=True),
        ),
    ]
