# Generated by Django 4.0.1 on 2022-03-25 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0037_alter_oldtractor_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oldtractor',
            name='KMDriven',
        ),
    ]
