# Generated by Django 4.0.1 on 2022-04-12 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0038_remove_oldtractor_kmdriven'),
    ]

    operations = [
        migrations.CreateModel(
            name='WishItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(blank=True, max_length=100, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('HP', models.CharField(blank=True, max_length=2, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='oldtractor',
            name='year',
        ),
        migrations.AddField(
            model_name='oldtractor',
            name='Back_Photo',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='oldtractor',
            name='Capacity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='oldtractor',
            name='ChassisNo',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='oldtractor',
            name='Color',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='oldtractor',
            name='Detail',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='oldtractor',
            name='Engine1_Photo',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='oldtractor',
            name='EngineNo',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='oldtractor',
            name='Engine_Photo',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='oldtractor',
            name='Front_Photo',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='oldtractor',
            name='Leftside_Photo',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='oldtractor',
            name='Manufacturingyear',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='oldtractor',
            name='Meter_Photo',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='oldtractor',
            name='OwnerNumber',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='oldtractor',
            name='RCStatus',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='oldtractor',
            name='RTOName',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='oldtractor',
            name='Registeryear',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='oldtractor',
            name='Rightside_Photo',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='oldtractor',
            name='Trollyhook',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='oldtractor',
            name='Tyare1_Photo',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='oldtractor',
            name='Tyare2_Photo',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='oldtractor',
            name='Tyare3_Photo',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='oldtractor',
            name='Tyare4_Photo',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='oldtractor',
            name='TyareLife1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='oldtractor',
            name='TyareLife2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='oldtractor',
            name='TyareLife3',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='oldtractor',
            name='TyareLife4',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='oldtractor',
            name='VehicalMake',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='oldtractor',
            name='Video',
            field=models.FileField(blank=True, null=True, upload_to='videos_uploaded'),
        ),
        migrations.AddField(
            model_name='oldtractor',
            name='color1',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='oldtractor',
            name='HP',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='oldtractor',
            name='Hours',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stoke',
            name='RegistrationNO',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
