# Generated by Django 4.0.1 on 2022-04-13 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0039_wishitem_remove_oldtractor_year_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WishList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload', models.ImageField(blank=True, null=True, upload_to='images')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='WishItem',
        ),
    ]
