# Generated by Django 4.0.1 on 2022-04-13 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0040_wishlist_delete_wishitem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OLDTRACTOR',
        ),
    ]
