# Generated by Django 4.0.1 on 2022-04-13 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0041_delete_oldtractor'),
    ]

    operations = [
        migrations.CreateModel(
            name='OldTractor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload', models.ImageField(blank=True, null=True, upload_to='images')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('HP', models.IntegerField(blank=True, null=True)),
                ('Manufacturingyear', models.IntegerField(blank=True, null=True)),
                ('Regno', models.CharField(blank=True, max_length=10, null=True)),
                ('RC', models.CharField(blank=True, max_length=3, null=True)),
                ('price', models.CharField(blank=True, max_length=6, null=True)),
                ('Hours', models.IntegerField(blank=True, null=True)),
                ('Registeryear', models.IntegerField(blank=True, null=True)),
                ('Detail', models.CharField(blank=True, max_length=100, null=True)),
                ('RTOName', models.CharField(blank=True, max_length=20, null=True)),
                ('OwnerNumber', models.IntegerField(blank=True, null=True)),
                ('VehicalMake', models.CharField(blank=True, max_length=10, null=True)),
                ('Color', models.CharField(blank=True, max_length=6, null=True)),
                ('ChassisNo', models.CharField(blank=True, max_length=20, null=True)),
                ('EngineNo', models.CharField(blank=True, max_length=20, null=True)),
                ('RCStatus', models.CharField(blank=True, max_length=3, null=True)),
                ('Capacity', models.IntegerField(blank=True, null=True)),
                ('Trollyhook', models.CharField(blank=True, max_length=10, null=True)),
                ('color1', models.CharField(blank=True, max_length=10, null=True)),
                ('Rightside_Photo', models.ImageField(blank=True, null=True, upload_to='images')),
                ('Leftside_Photo', models.ImageField(blank=True, null=True, upload_to='images')),
                ('Meter_Photo', models.ImageField(blank=True, null=True, upload_to='images')),
                ('Front_Photo', models.ImageField(blank=True, null=True, upload_to='images')),
                ('Back_Photo', models.ImageField(blank=True, null=True, upload_to='images')),
                ('Tyare1_Photo', models.ImageField(blank=True, null=True, upload_to='images')),
                ('TyareLife1', models.IntegerField(blank=True, null=True)),
                ('Tyare2_Photo', models.ImageField(blank=True, null=True, upload_to='images')),
                ('TyareLife2', models.IntegerField(blank=True, null=True)),
                ('Tyare3_Photo', models.ImageField(blank=True, null=True, upload_to='images')),
                ('TyareLife3', models.IntegerField(blank=True, null=True)),
                ('Tyare4_Photo', models.ImageField(blank=True, null=True, upload_to='images')),
                ('TyareLife4', models.IntegerField(blank=True, null=True)),
                ('Engine_Photo', models.ImageField(blank=True, null=True, upload_to='images')),
                ('Engine1_Photo', models.ImageField(blank=True, null=True, upload_to='images')),
                ('Video', models.FileField(blank=True, null=True, upload_to='videos_uploaded')),
            ],
        ),
    ]
