# Generated by Django 4.0.1 on 2022-04-13 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0042_oldtractor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wishlist',
            old_name='name',
            new_name='name1',
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='upload',
        ),
        migrations.AddField(
            model_name='wishlist',
            name='price',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
