# Generated by Django 4.0.1 on 2022-04-13 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0045_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='oldtractor',
            name='is_sold_out',
            field=models.BooleanField(default=False),
        ),
    ]
