# Generated by Django 4.0.1 on 2022-04-15 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0046_oldtractor_is_sold_out'),
    ]

    operations = [
        migrations.AddField(
            model_name='oldtractor',
            name='year_in_school',
            field=models.CharField(choices=[('FR', 'Freshman'), ('SO', 'Sophomore'), ('JR', 'Junior'), ('SR', 'Senior'), ('GR', 'Graduate')], default='FR', max_length=2),
        ),
    ]
