# Generated by Django 4.0.1 on 2022-04-15 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0048_remove_oldtractor_year_in_school'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oldtractor',
            name='Front_Photo',
        ),
    ]
