# Generated by Django 4.0.1 on 2022-04-19 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0050_contactenquiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactenquiry',
            name='Phone_number',
            field=models.IntegerField(blank=True, max_length=10, null=True),
        ),
    ]
