# Generated by Django 4.0.1 on 2022-04-20 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0051_alter_contactenquiry_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery_image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.ImageField(blank=True, null=True, upload_to='images')),
            ],
        ),
    ]
