# Generated by Django 4.0.1 on 2022-04-21 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0052_gallery_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='oldtractor',
            name='Min_Prize',
            field=models.IntegerField(blank=True, max_length=6, null=True),
        ),
    ]
