# Generated by Django 4.0.1 on 2022-04-21 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0054_oldtractor_hp1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oldtractor',
            name='HP1',
        ),
    ]
