# Generated by Django 4.0.1 on 2022-04-25 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0056_remove_oldtractor_name_alter_oldtractor_upload'),
    ]

    operations = [
        migrations.AddField(
            model_name='oldtractor',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='oldtractor',
            name='upload',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
