# Generated by Django 4.0.1 on 2022-04-25 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0058_alter_oldtractor_back_photo_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='destination',
        ),
    ]
