# Generated by Django 4.0.1 on 2022-04-25 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0059_delete_destination'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactenquiry',
            name='Phone_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='oldtractor',
            name='Min_Prize',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
