# Generated by Django 4.0.1 on 2022-04-25 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0060_alter_contactenquiry_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oldtractor',
            name='upload',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
