# Generated by Django 4.0.1 on 2022-04-28 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0061_alter_oldtractor_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oldtractor',
            name='upload',
            field=models.ImageField(upload_to='images'),
        ),
    ]
