# Generated by Django 4.0.1 on 2022-05-02 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0066_remove_oldtractor_color_remove_oldtractor_min_prize'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gallery_image',
            old_name='Image',
            new_name='upload1',
        ),
    ]
