# Generated by Django 4.0.1 on 2022-05-06 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0067_rename_image_gallery_image_upload1'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Wishlist',
        ),
    ]
